cpp : 
   codes :
      properties : 
          E0001 : 用户凭证过期，请重新登录
          E0002 : 后台错误，请联系管理员
          E0003 : 验证码错误/过期
          E0004 : 短信验证码错误
          E0005 : 短信验证码过期
          E0006 : 用户账号已存在！
          E0007 : 短信验证码获取次数过多